services:
  ulp_bot:
    build: .
    container_name: ulp_bot
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - shared_network
    environment:
      - CLIENT_ID=client_a
      - TELEGRAM_TOKEN=12345:ABC...
      - CORE_API_URL=http://admin_api:8000
      - PYTHONUNBUFFERED=1

networks:
  shared_network:
    external: true